spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: book-service
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/v1/books/**

            - id: lending-service
              uri: lb://LENDING-SERVICE
              predicates:
                - Path=/api/v1/lendings/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"

server:
  port: 7000